# Population Density Data
Data is unfortunately from the 2010 US Census, and appears to be the most recent available from the census

The following links are relavant:
 https://www.census.gov/data/tables/2010/dec/density-data-text.html
* https://www.census.gov/2010census/data/apportionment-data-map.html

Data for this analysis found here:
* https://www2.census.gov/programs-surveys/decennial/tables/2010/2010-apportionment/pop_density.csv

In [1]:
import pandas as pd

In [2]:
url="https://www2.census.gov/programs-surveys/decennial/tables/2010/2010-apportionment/pop_density.csv"
data = pd.read_csv(url)

In [5]:
data.tail(15)

,# POPULATION DENSITY DATA PROVIDED BY U.S. CENSUS.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
41,Oregon,672765,783389,953786,1089684,1521341,1768687,2091385,2633105,2842321,...,44,42,41,41,40,40,41,42,41,41
42,Pennsylvania,7665111,8720017,9631350,9900180,10498012,11319366,11793909,11863895,11881643,...,8,8,8,9,9,10,10,10,12,11
43,Rhode Island,542610,604397,687497,713346,791896,859488,946725,947154,1003464,...,2,2,2,3,2,3,4,4,4,4
44,South Carolina,1515400,1683724,1738765,1899804,2117027,2382594,2590516,3121820,3486703,...,19,20,21,21,21,21,21,22,23,22
45,South Dakota,583888,636547,692849,642961,652740,680514,665507,690768,696004,...,43,44,44,44,46,46,48,49,48,48
46,Tennessee,2184789,2337885,2616556,2915841,3291718,3567089,3923687,4591120,4877185,...,18,18,18,18,20,20,20,21,21,21
47,Texas,3896542,4663228,5824715,6414824,7711194,9579677,11196730,14229191,16986510,...,39,39,38,38,35,35,32,31,30,28
48,Utah,373351,449396,507847,550310,688862,890627,1059273,1461037,1722850,...,45,45,45,45,44,44,44,43,43,43
49,Vermont,355956,352428,359611,359231,377747,389881,444330,511456,562758,...,30,30,31,32,34,32,31,32,32,32
50,Virginia,2061612,2309187,2421851,2677773,3318680,3966949,4648494,5346818,6187358,...,17,19,19,16,16,18,18,17,16,16
51,Washington,1141990,1356621,1563396,1736191,2378963,2853214,3409169,4132156,4866692,...,37,37,37,35,32,30,30,30,27,27
52,West Virginia,1221119,1463701,1729205,1901974,2005552,1860421,1744237,1949644,1793477,...,15,15,15,15,22,27,27,28,31,31
53,Wisconsin,2333860,2632067,2939006,3137587,3434575,3951777,4417731,4705767,4891769,...,24,22,22,23,25,24,26,26,26,25
54,Wyoming,145965,194402,225565,250742,290529,330066,332416,469557,453588,...,50,50,50,50,50,51,51,51,51,51
55,Puerto Rico,1118012,1299809,1543913,1869255,2210703,2349544,2712033,3196520,3522037,...,5,5,5,2,4,4,3,3,3,3