In [1]:
# See covid_virtual_env.sh for environment setup
import boto3, pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_rows', 500)

# Load Data

Set the client for boto3 (amazons toolkit) to read s3

In [2]:
client = boto3.client('s3')

In [16]:
# New York Times Data
obj = client.get_object(Bucket='covid19-lake', Key='rearc-covid-19-prediction-models/csv/county-predictions/county-predictions.csv')
data = pd.read_csv(obj['Body'])

# Data Exploration

## Fundamental exploration
What values are showing up?

In [18]:
# Quick look at the records
data.head()

,countyfips,countyname,statename,predicted_deaths_by_may_16,predicted_deaths_intervals_by_may_16,predicted_deaths_by_may_17,predicted_deaths_intervals_by_may_17,predicted_deaths_by_may_18,predicted_deaths_intervals_by_may_18,predicted_deaths_by_may_19,predicted_deaths_intervals_by_may_19,predicted_deaths_by_may_20,predicted_deaths_intervals_by_may_20,predicted_deaths_by_may_21,predicted_deaths_intervals_by_may_21,predicted_deaths_by_may_22,predicted_deaths_intervals_by_may_22,severity_county_5-day
0,36047,Kings,NY,6274.7,"(6227.68973581044, 6320.154825858874)",6331.8,"(6221.340718754236, 6439.404419187793)",6389.1,"(6240.954949744417, 6533.479575671505)",6446.7,"(6263.985525990299, 6624.970408243806)",6504.3,"(6307.665383150776, 6696.672392424249)",6561.7,"(6335.072297988258, 6785.591696003429)",6619.0,"(6359.2789972142755, 6878.736921664969)",3
1,36081,Queens,NY,5955.1,"(5930, 5982.1357984414535)",5983.2,"(5930, 6054.711740406734)",6011.4,"(5930, 6188.443103795347)",6039.6,"(5930, 6270.328139393472)",6067.8,"(5930, 6355.670213794322)",6095.8,"(5930, 6449.231341250369)",6123.6,"(5930, 6526.808614406045)",3
2,36005,Bronx,NY,4003.3,"(3973.9252036713187, 4030.8126065457286)",4035.6,"(3977.7939750935166, 4090.0405131128105)",4068.0,"(3984.0840699027194, 4147.484180538256)",4100.5,"(3998.8445109734894, 4197.123197404594)",4132.9,"(4015.7527018225483, 4245.298550981924)",4165.0,"(4027.6780439555355, 4299.226270684399)",4196.8,"(3970, 4452.394304906323)",3
3,17031,Cook,IL,2891.1,"(2787.8396886119135, 2982.33727721182)",3013.2,"(2874.338110717161, 3129.9810449896668)",3137.5,"(2924.892600893215, 3319.7921932115178)",3262.6,"(2992.9844597710294, 3499.023621757375)",3388.2,"(3080.115471682737, 3667.0684104701186)",3514.1,"(3231.792325041693, 3776.542521415358)",3639.2,"(3312.5079647497273, 3965.8886217972436)",3
4,36061,New York,NY,2564.3,"(2537, 2583.176893306037)",2592.0,"(2537, 2636.768389644343)",2619.2,"(2537, 2707.956020725296)",2645.3,"(2537, 2797.6965292177542)",2669.6,"(2537, 2867.1028382305185)",2690.9,"(2537, 2934.916096382429)",2709.1,"(2537, 3002.681094629235)",3